## Hydra Settings ##
defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

hydra:
  run:
    dir: .
  output_subdir: null
  sweep:
    dir: .
    subdir: .


## WanDB Settings ##
wandb:
    project: pml-defect
    run_name: ''
    tags: [baseline]
    notes: ''
    data_dir: ${img_dir}
    model_name: 'convnext_base'


## User Settings ##
img_dir: '/content/drive/MyDrive/Colab Notebooks/pml_defect/input/train_data'
train_master_dir: '/content/drive/MyDrive/Colab Notebooks/pml_defect/input/train.csv'
save_model_dir: '/content/drive/MyDrive/Colab Notebooks/pml_defect/model'
num_classes: 2
embedding_size: 512
image_size: 224
seed: 0
epochs: 50


train_test_split:
    test_size: 0.25
    random_state: 42

train_dataloader:
    batch_size: 4
    shuffle: True
    num_workers: 2
    pin_memory: True

val_dataloader:
    batch_size: 1
    shuffle: False # DO NOT CHANGE!!!
    num_workers: 2
    pin_memory: True
  
train_transform:
    resize:
        image_size: ${image_size}
    random_horizontal_flip:
        p: 0.5
    random_vertical_flip:
        p: 0.5
    random_rotation:
        degrees: 20
    random_affine:
        degrees: [-90, 90]
        translate: [0, 0]
        scale: [1.0, 1.0]
        shear: [-0.2, 0.2]
    color_jitter:
        brightness: 0.1
        contrast: 0.1
        saturation: 0.1
        hue: 0
    normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

test_transform:
    resize:
        image_size: ${image_size}
    normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

convnext_base:
    pretrained: True

accuracy_calculator:
    k: 'max_bin_count'

optimizer:
    name: Adam
    adam:
        lr: 1e-4
        weight_decay: 1e-5
    sgd:
        lr: 1e-4
        weight_decay: 1e-5

scheduler:
    name: CosineAnnealingWarmRestarts
    CosineAnnealingWarmRestarts:
        T_0: 10
        eta_min: 1e-6

earlystopping:
    patience: 100
    verbose: 1