## Hydra Settings ##
defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

hydra:
  run:
    dir: .
  output_subdir: null
  sweep:
    dir: .
    subdir: .

## User Settings ##
timm_name: convnext_base
wandb_run_path: insilicomab/defect/3pu9avb9
model_name: rose-rain-5
image_size: 224


train_transform:
    resize:
        image_size: ${image_size}
    random_horizontal_flip:
        p: 0.5
    random_vertical_flip:
        p: 0.5
    random_rotation:
        degrees: 20
    random_affine:
        degrees: [-90, 90]
        translate: [0, 0]
        scale: [1.0, 1.0]
        shear: [-0.2, 0.2]
    color_jitter:
        brightness: 0.1
        contrast: 0.1
        saturation: 0.1
        hue: 0
    normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

test_transform:
    resize:
        image_size: ${image_size}
    normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]